#! /bin/bash

SAVEPOINT="$3"
ARGUMENTS=${@:4}

PROCESS=0
FILE1="/home/christian/workspace/icon-test-lesturb/experiments/nh_weisman_klemp/serializer_clouds_twomoment_${1}_${PROCESS}_${2}.dat"
FILE2="/home/christian/workspace/icon-test-lesturb/experiments/icon-testbed_twomom/serializer_clouds_twomoment_${1}_${PROCESS}_${2}.dat"

echo "./compare "$FILE1" "$FILE2" "$SAVEPOINT" $ARGUMENTS"
./compare "$FILE1" "$FILE2" "$SAVEPOINT" $ARGUMENTS

#PROCESS=1
#FILE1="/home/christian/workspace/icon-test-lesturb/experiments/nh_weisman_klemp/serializer_clouds_twomoment_${1}_${PROCESS}_${2}.dat"
#FILE2="/home/christian/workspace/icon-test-lesturb/experiments/icon-testbed_twomom/serializer_clouds_twomoment_${1}_${PROCESS}_${2}.dat"
#
#echo "./compare "$FILE1" "$FILE2" "$SAVEPOINT" $ARGUMENTS"
#./compare "$FILE1" "$FILE2" "$SAVEPOINT" $ARGUMENTS


exit 0


