#! /bin/bash

FILE="/home/christian/workspace/icon-test-lesturb/experiments/${1}/serializer_clouds_twomoment_${2}_${3}_${4}.dat"
SAVEPOINT="$5"
ARGUMENTS=${@:6}

# echo "FILE: $FILE"
# echo "SAVEPOINT: $SAVEPOINT"

./dump "$FILE" "$SAVEPOINT" $ARGUMENTS

exit 0


