#! /bin/bash

PROCESS=1
FILE1="/home/christian/workspace/icon-test-lesturb/experiments/nh_cbl/serializer_diffuse_hori_velocity_${1}_${PROCESS}_${2}.dat"
FILE2="/home/christian/workspace/icon-test-lesturb/experiments/icon-testbed_sgsturb_torus/serializer_diffuse_hori_velocity_${1}_${PROCESS}_${2}.dat"
SAVEPOINT="$1"
ARGUMENTS=${@:3}

# echo "FILE1: $FILE1"
# echo "FILE2: $FILE2"
# echo "SAVEPOINT: $SAVEPOINT"

./compare "$FILE1" "$FILE2" "$SAVEPOINT" $ARGUMENTS

exit 0


